services:
  - type: web
    name: storyteller-api
    dockerfilePath: ./storyteller-api/Dockerfile
    dockerContext: ./storyteller-api
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.5" # Using a specific, stable Python version
      - key: GCP_PROJECT_ID
        value: "internal-api-usage-alternate"
